--!nocheck
-- Generado por generar_modulo_catalogo.py. No editar a mano:
-- vuelve a ejecutarlo tras publicar los lugares para rellenar placeId.

return {
	{
		titulo = "arena2s_Place",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 72045704635788,
	},
	{
		titulo = "Base Wars Fortress Assault",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 71987569565451,
	},
	{
		titulo = "Battlefield ROBLOX - NXT GEN BrickBattle v1",
		creador = "jediknightkrazy",
		categoria = "Brickbattle y combate",
		procedencia = "uncopylocked",
		anio = 2008,
		placeId = 106441738420780,
	},
	{
		titulo = "BlankArenas_Place",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 118648632442082,
	},
	{
		titulo = "Blender",
		creador = "clockwork",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 131986942393926,
	},
	{
		titulo = "Busted Arena",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 74854223163925,
	},
	{
		titulo = "Castle Warfare",
		creador = "builderman",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 124292701167885,
	},
	{
		titulo = "Classic Crossroads",
		creador = "ROBLOX",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		anio = 2009,
		placeId = 117701427215780,
	},
	{
		titulo = "Classic Rocket Arena",
		creador = "ROBLOX",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 72564783739583,
	},
	{
		titulo = "Crazy Car Wars",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 121037143401557,
	},
	{
		titulo = "CTF Template",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 139164662658259,
	},
	{
		titulo = "CTF Template Demo",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 125086361537476,
	},
	{
		titulo = "Four Towers Bridge Battle",
		creador = "builderman",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 115360580959336,
	},
	{
		titulo = "Gravity Hammer Fight",
		creador = "clockwork",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 89640916571730,
	},
	{
		titulo = "My giant sword",
		creador = "ReeseMcBlox",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 135713322255239,
	},
	{
		titulo = "Ninjas vs Samurai Pagoda Battle",
		creador = "builderman",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 104837801586132,
	},
	{
		titulo = "ReeseMcBlox_s Place",
		creador = "ReeseMcBlox",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 103141615305746,
	},
	{
		titulo = "ROBLOX Base Wars FPS",
		creador = "Games",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 91359576733361,
	},
	{
		titulo = "ROBLOX Battle",
		creador = "Games",
		categoria = "Brickbattle y combate",
		procedencia = "uncopylocked",
		placeId = 89549367311553,
	},
	{
		titulo = "Rocket Fight Advanced",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 118195877602576,
	},
	{
		titulo = "Set 1",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 138256458635994,
	},
	{
		titulo = "Set 2",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 100497839528843,
	},
	{
		titulo = "Snow",
		creador = "clockwork",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 136558016494120,
	},
	{
		titulo = "Sword Fight in the DARK",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 85751302340704,
	},
	{
		titulo = "Sword Fight on the Heights III",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 80559627691132,
	},
	{
		titulo = "Sword Fights on the Heights II",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 76035112241513,
	},
	{
		titulo = "Sword Fights on the Heights IV",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 88159598299325,
	},
	{
		titulo = "Sword Fights on the Heights IV 10 14",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		anio = 2008,
		placeId = 104552428034550,
	},
	{
		titulo = "Sword Fights on the Heights Original",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 136791380976153,
	},
	{
		titulo = "Sword Training",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 70793464414237,
	},
	{
		titulo = "TAG CTF YAY",
		creador = "ReeseMcBlox",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 111282948534672,
	},
	{
		titulo = "Trampoline_Sword_Fight",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 132666660396509,
	},
	{
		titulo = "Upgrade Wars v1.52",
		creador = "clockwork",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 126650895722550,
	},
	{
		titulo = "Vampires Vs. Werewolves CTF",
		creador = "ROBLOX",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 105727325798025,
	},
	{
		titulo = "Weapon Pickup Bug",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 76714327868456,
	},
	{
		titulo = "Wishing Castle",
		creador = "builderman",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 114322813640910,
	},
	{
		titulo = "Wooden Crossroads",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 70991510880607,
	},
	{
		titulo = "Ye Olde Sword Shoppe",
		creador = "Shedletsky",
		categoria = "Brickbattle y combate",
		procedencia = "oficial",
		placeId = 81435907350800,
	},
	{
		titulo = "2D Land",
		creador = "clockwork",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 98061725331225,
	},
	{
		titulo = "A Bridge Too Far",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 82973593857191,
	},
	{
		titulo = "Another Jedi Labs",
		creador = "jediknightkrazy",
		categoria = "Clasicos varios",
		procedencia = "uncopylocked",
		anio = 2008,
		placeId = 121404793914692,
	},
	{
		titulo = "Another Jedi Labs Again",
		creador = "jediknightkrazy",
		categoria = "Clasicos varios",
		procedencia = "uncopylocked",
		anio = 2009,
		placeId = 114379784585441,
	},
	{
		titulo = "Area 51",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 98426163402780,
	},
	{
		titulo = "Astroland",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 72215522407694,
	},
	{
		titulo = "Bounty Hunter - FIXED - UNCOPYLOCKED",
		creador = "jediknightkrazy",
		categoria = "Clasicos varios",
		procedencia = "uncopylocked",
		anio = 2010,
		placeId = 111986089125049,
	},
	{
		titulo = "BUG Decal Glitch for hansong",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 102761145713260,
	},
	{
		titulo = "Building Place",
		creador = "david.baszucki",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		anio = 2010,
		placeId = 89955209247116,
	},
	{
		titulo = "Business Sim",
		creador = "Templates",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 92799889985363,
	},
	{
		titulo = "Classic Chaos Canyon",
		creador = "ROBLOX",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 86262233287221,
	},
	{
		titulo = "clockwork_s Sound System",
		creador = "clockwork",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 107959340744559,
	},
	{
		titulo = "Community_Construction",
		creador = "ROBLOX",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 100397799268240,
	},
	{
		titulo = "Construction-Room-Save",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 110263789430999,
	},
	{
		titulo = "Conway s Game of Life",
		creador = "erik.cassel",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 134577629189276,
	},
	{
		titulo = "COW CLICKER Data Persistence Demo",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 108475443384656,
	},
	{
		titulo = "DEATHBENCH",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 121272165015063,
	},
	{
		titulo = "Dodge Stuff",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 121881343968993,
	},
	{
		titulo = "Doll 7Place",
		creador = "david.baszucki",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		anio = 2007,
		placeId = 70884684227068,
	},
	{
		titulo = "Domino Rally",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 97244242366917,
	},
	{
		titulo = "DUCK",
		creador = "clockwork",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 95425999245281,
	},
	{
		titulo = "Elemental Lake",
		creador = "builderman",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 136172460928123,
	},
	{
		titulo = "Emerald Forest",
		creador = "builderman",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 72805367993430,
	},
	{
		titulo = "Experimental jet pack",
		creador = "erik.cassel",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 119561781645519,
	},
	{
		titulo = "Explosions Every 30 Seconds Or Your Money Back",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 123395851160847,
	},
	{
		titulo = "Fire Stress Test",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 88120577983793,
	},
	{
		titulo = "Fun with Mjolnir",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 113876465341351,
	},
	{
		titulo = "Gauntlet",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 92814743893181,
	},
	{
		titulo = "Gears",
		creador = "clockwork",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 84737689772309,
	},
	{
		titulo = "Get TelaTwitters",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 79160942811590,
	},
	{
		titulo = "Grand_Melee_FINAL_ROUND_IS_OVER",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 115380261586758,
	},
	{
		titulo = "Guitar",
		creador = "stoecker",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 128994256014441,
	},
	{
		titulo = "HERE-where-the-world-is-quiet",
		creador = "Swinburne",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 73459987384264,
	},
	{
		titulo = "Hoop Ride 1.3",
		creador = "clockwork",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 114987484676629,
	},
	{
		titulo = "Jedi Labs",
		creador = "jediknightkrazy",
		categoria = "Clasicos varios",
		procedencia = "uncopylocked",
		anio = 2008,
		placeId = 108428972502252,
	},
	{
		titulo = "Jedi Labs AI testing",
		creador = "jediknightkrazy",
		categoria = "Clasicos varios",
		procedencia = "uncopylocked",
		anio = 2008,
		placeId = 101700188814153,
	},
	{
		titulo = "Just Some Stuff",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 99558852489070,
	},
	{
		titulo = "King of the Hill v1.5 UPDATED",
		creador = "builderman",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 93176908637810,
	},
	{
		titulo = "Ladder and Force Field Test Level",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 82276414118721,
	},
	{
		titulo = "Liminal Message",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 80336729802585,
	},
	{
		titulo = "Martian Invasion",
		creador = "builderman",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 70788809553127,
	},
	{
		titulo = "MASSIVE LAG WORLD",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 120725352372368,
	},
	{
		titulo = "Mayhem",
		creador = "Matt Dusek",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 85618115101167,
	},
	{
		titulo = "Mission to the Moon",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 92428170041143,
	},
	{
		titulo = "Mountain",
		creador = "Templates",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 79269504858128,
	},
	{
		titulo = "Nevermoor_s Blight",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 92510280888467,
	},
	{
		titulo = "NukeTheWhales",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 82098390497685,
	},
	{
		titulo = "Personal Server Starting Place",
		creador = "ROBLOX",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 103374824566815,
	},
	{
		titulo = "Pinball Wizards",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 130478941430427,
	},
	{
		titulo = "Quick Office Building",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 78992160984191,
	},
	{
		titulo = "Rainbow Road 1.5",
		creador = "clockwork",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 84173027620120,
	},
	{
		titulo = "Ro-Quake_DM17_-_The_Longest_Yard",
		creador = "dm17",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 134988601317405,
	},
	{
		titulo = "ROBLOX Thanksgiving Hunt",
		creador = "ROBLOX",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		anio = 2009,
		placeId = 115686455061671,
	},
	{
		titulo = "ROBLOX Thanksgiving Turkey Hunt",
		creador = "ROBLOX",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 81664575954355,
	},
	{
		titulo = "Robloxia_s Last Stand",
		creador = "clockwork",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 138624413865762,
	},
	{
		titulo = "Robloxopolis",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		anio = 2007,
		placeId = 95293267541000,
	},
	{
		titulo = "ROBLOXs-Place",
		creador = "david.baszucki",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 80173700359784,
	},
	{
		titulo = "Rocket Mayhem",
		creador = "erik.cassel",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 89802324837851,
	},
	{
		titulo = "Santas-Winter-Stronghold",
		creador = "ROBLOX",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 107603373642870,
	},
	{
		titulo = "Satellite",
		creador = "clockwork",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 74727738428826,
	},
	{
		titulo = "See Desc",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		anio = 2009,
		placeId = 138737837420776,
	},
	{
		titulo = "Skyscraper",
		creador = "Matt Dusek",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 74630604315690,
	},
	{
		titulo = "Sparkle and ClickDetector Demo",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 104929517291345,
	},
	{
		titulo = "Starting Place",
		creador = "Templates",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 73708997818523,
	},
	{
		titulo = "Suburban",
		creador = "Templates",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 91737378722349,
	},
	{
		titulo = "Telamons_Big_World",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 72948230698456,
	},
	{
		titulo = "TEstsETtseT",
		creador = "stoecker",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 110867923933149,
	},
	{
		titulo = "The endless hole - v1.0",
		creador = "jediknightkrazy",
		categoria = "Clasicos varios",
		procedencia = "uncopylocked",
		anio = 2008,
		placeId = 116244150857487,
	},
	{
		titulo = "The Vanishing Point",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 78572479512557,
	},
	{
		titulo = "Timmy and the Killbots",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		anio = 2007,
		placeId = 124229440282055,
	},
	{
		titulo = "TMNT",
		creador = "Sponsored Events",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 90006028066430,
	},
	{
		titulo = "Truss and Slate and Badges Demo",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 97922157420752,
	},
	{
		titulo = "Turkey Hunt - Come Get Free Stuff",
		creador = "ROBLOX",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		anio = 2010,
		placeId = 106785525298448,
	},
	{
		titulo = "Ultimate Build",
		creador = "B0BBA",
		categoria = "Clasicos varios",
		procedencia = "uncopylocked",
		anio = 2010,
		placeId = 109631589821500,
	},
	{
		titulo = "Unknown Hat Testing Game",
		creador = "ROBLOX",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 70792784283646,
	},
	{
		titulo = "Unknown Testing Place #2",
		creador = "ROBLOX",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 134922924284650,
	},
	{
		titulo = "unnamed",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 100120441012214,
	},
	{
		titulo = "Weapons Testing",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 138757091334340,
	},
	{
		titulo = "Welcome to ROBLOX Building",
		creador = "ROBLOX",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 109372923970995,
	},
	{
		titulo = "Welcome to Stoogeville",
		creador = "Sponsored Events",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 81951151617434,
	},
	{
		titulo = "Western",
		creador = "Templates",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 117625452874465,
	},
	{
		titulo = "Yet Another Jedi Labs",
		creador = "jediknightkrazy",
		categoria = "Clasicos varios",
		procedencia = "uncopylocked",
		anio = 2009,
		placeId = 121890019738729,
	},
	{
		titulo = "ZACK ATTACK",
		creador = "Shedletsky",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 113927004533754,
	},
	{
		titulo = "Zeke and Luther Skate Park",
		creador = "ROBLOX",
		categoria = "Clasicos varios",
		procedencia = "oficial",
		placeId = 129433451120066,
	},
	{
		titulo = "Balance",
		creador = "Matt Dusek",
		categoria = "Desastres y fisica",
		procedencia = "oficial",
		placeId = 136692002915969,
	},
	{
		titulo = "Builderman_s Vacation Sim Relax to survive",
		creador = "builderman",
		categoria = "Desastres y fisica",
		procedencia = "oficial",
		placeId = 95741326939755,
	},
	{
		titulo = "Classic Dodge the Teapots of Doom",
		creador = "clockwork",
		categoria = "Desastres y fisica",
		procedencia = "oficial",
		placeId = 133020607226408,
	},
	{
		titulo = "New Server Physics Benchmark",
		creador = "Shedletsky",
		categoria = "Desastres y fisica",
		procedencia = "oficial",
		placeId = 112579471688142,
	},
	{
		titulo = "Survive the Spheres",
		creador = "ss1122",
		categoria = "Desastres y fisica",
		procedencia = "uncopylocked",
		anio = 2010,
		placeId = 139745623596018,
	},
	{
		titulo = "Tornado",
		creador = "clockwork",
		categoria = "Desastres y fisica",
		procedencia = "uncopylocked",
		placeId = 97892604648224,
	},
	{
		titulo = "Longest Lava Jump Obby -21 000 Jumps- Uncopylocked",
		creador = "KnightsAndNoobs",
		categoria = "Obbies y parkour",
		procedencia = "uncopylocked",
		placeId = 91562053824706,
	},
	{
		titulo = "Obstacle Courses are getting old",
		creador = "clockwork",
		categoria = "Obbies y parkour",
		procedencia = "oficial",
		placeId = 118172830352107,
	},
	{
		titulo = "Two Player Obby Tycoon Uncopylocked",
		creador = "Chicharito1000",
		categoria = "Obbies y parkour",
		procedencia = "uncopylocked",
		placeId = 132523658595322,
	},
	{
		titulo = "BENCHMARK",
		creador = "Shedletsky",
		categoria = "Rol y ciudades",
		procedencia = "oficial",
		placeId = 72358965677289,
	},
	{
		titulo = "BrightEyes s Purpletopia of Awesome Joy",
		creador = "BrightEyes",
		categoria = "Rol y ciudades",
		procedencia = "oficial",
		placeId = 116639747487875,
	},
	{
		titulo = "Classic Glass Houses",
		creador = "ROBLOX",
		categoria = "Rol y ciudades",
		procedencia = "oficial",
		placeId = 87154146101376,
	},
	{
		titulo = "clockwork s quest v1.09 - RPG - SAVESYSTEM - Magic",
		creador = "clockwork",
		categoria = "Rol y ciudades",
		procedencia = "oficial",
		placeId = 74941913923041,
	},
	{
		titulo = "Home for the Holidays",
		creador = "Shedletsky",
		categoria = "Rol y ciudades",
		procedencia = "oficial",
		placeId = 74121224475347,
	},
	{
		titulo = "Overpowered Terrain Demo",
		creador = "Shedletsky",
		categoria = "Rol y ciudades",
		procedencia = "oficial",
		placeId = 117279602842319,
	},
	{
		titulo = "Roblox HQ - clockwork",
		creador = "clockwork",
		categoria = "Rol y ciudades",
		procedencia = "oficial",
		placeId = 121574601797308,
	},
	{
		titulo = "Roblox HQ 2.0",
		creador = "builderman",
		categoria = "Rol y ciudades",
		procedencia = "oficial",
		placeId = 104940483821672,
	},
	{
		titulo = "ROBLOX World Headquarters (Shedletsky)",
		creador = "Shedletsky",
		categoria = "Rol y ciudades",
		procedencia = "oficial",
		placeId = 101843209946951,
	},
	{
		titulo = "ROBLOX World Headquarters (builderman)",
		creador = "builderman",
		categoria = "Rol y ciudades",
		procedencia = "oficial",
		anio = 2006,
		placeId = 94107404897457,
	},
	{
		titulo = "Telamon s Mad House",
		creador = "Shedletsky",
		categoria = "Rol y ciudades",
		procedencia = "oficial",
		placeId = 105151565607803,
	},
	{
		titulo = "Keyboard controlled police cars. UNCOPYLOCKED",
		creador = "ROBLOX",
		categoria = "Vehiculos y tycoons",
		procedencia = "uncopylocked",
		anio = 2007,
		placeId = 130560352150720,
	},
	{
		titulo = "Ride a Cart Into My Face",
		creador = "Shedletsky",
		categoria = "Vehiculos y tycoons",
		procedencia = "oficial",
		placeId = 74392290203439,
	},
	{
		titulo = "Rocket Car Rally",
		creador = "Shedletsky",
		categoria = "Vehiculos y tycoons",
		procedencia = "oficial",
		placeId = 92006020054289,
	},
	{
		titulo = "Space Knights",
		creador = "RaceToTheBottom",
		categoria = "Vehiculos y tycoons",
		procedencia = "oficial",
		placeId = 137212337204243,
	},
	{
		titulo = "Haunted Hill",
		creador = "Shedletsky",
		categoria = "Zombis y terror",
		procedencia = "oficial",
		placeId = 139210804106256,
	},
	{
		titulo = "Nooooooo",
		creador = "ROBLOX",
		categoria = "Zombis y terror",
		procedencia = "uncopylocked",
		anio = 2010,
		placeId = 75113184635972,
	},
	{
		titulo = "YOUR HOUSE IS SURROEUNDED BY ZOMBIES",
		creador = "jediknightkrazy",
		categoria = "Zombis y terror",
		procedencia = "uncopylocked",
		anio = 2009,
		placeId = 106544989670742,
	},
}
