--!nocheck
-- Generado por generar_modulo_catalogo.py. No editar a mano:
-- vuelve a ejecutarlo tras publicar los lugares para rellenar placeId.

return {
	{
		titulo = "Battlefield ROBLOX - NXT GEN BrickBattle v1",
		creador = "jediknightkrazy",
		categoria = "Brickbattle y combate",
		procedencia = "uncopylocked",
		anio = 2008,
		placeId = 106441738420780,
	},
	{
		titulo = "ROBLOX Battle",
		creador = "Games",
		categoria = "Brickbattle y combate",
		procedencia = "uncopylocked",
		placeId = 89549367311553,
	},
	{
		titulo = "Another Jedi Labs",
		creador = "jediknightkrazy",
		categoria = "Clasicos varios",
		procedencia = "uncopylocked",
		anio = 2008,
		placeId = 121404793914692,
	},
	{
		titulo = "Another Jedi Labs Again",
		creador = "jediknightkrazy",
		categoria = "Clasicos varios",
		procedencia = "uncopylocked",
		anio = 2009,
		placeId = 114379784585441,
	},
	{
		titulo = "Bounty Hunter - FIXED - UNCOPYLOCKED",
		creador = "jediknightkrazy",
		categoria = "Clasicos varios",
		procedencia = "uncopylocked",
		anio = 2010,
		placeId = 111986089125049,
	},
	{
		titulo = "Jedi Labs",
		creador = "jediknightkrazy",
		categoria = "Clasicos varios",
		procedencia = "uncopylocked",
		anio = 2008,
		placeId = 108428972502252,
	},
	{
		titulo = "Jedi Labs AI testing",
		creador = "jediknightkrazy",
		categoria = "Clasicos varios",
		procedencia = "uncopylocked",
		anio = 2008,
		placeId = 101700188814153,
	},
	{
		titulo = "The endless hole - v1.0",
		creador = "jediknightkrazy",
		categoria = "Clasicos varios",
		procedencia = "uncopylocked",
		anio = 2008,
		placeId = 116244150857487,
	},
	{
		titulo = "Ultimate Build",
		creador = "B0BBA",
		categoria = "Clasicos varios",
		procedencia = "uncopylocked",
		anio = 2010,
		placeId = 109631589821500,
	},
	{
		titulo = "Yet Another Jedi Labs",
		creador = "jediknightkrazy",
		categoria = "Clasicos varios",
		procedencia = "uncopylocked",
		anio = 2009,
		placeId = 121890019738729,
	},
	{
		titulo = "Survive the Spheres",
		creador = "ss1122",
		categoria = "Desastres y fisica",
		procedencia = "uncopylocked",
		anio = 2010,
		placeId = 139745623596018,
	},
	{
		titulo = "Tornado",
		creador = "clockwork",
		categoria = "Desastres y fisica",
		procedencia = "uncopylocked",
		placeId = 97892604648224,
	},
	{
		titulo = "Longest Lava Jump Obby -21 000 Jumps- Uncopylocked",
		creador = "KnightsAndNoobs",
		categoria = "Obbies y parkour",
		procedencia = "uncopylocked",
		placeId = 91562053824706,
	},
	{
		titulo = "Two Player Obby Tycoon Uncopylocked",
		creador = "Chicharito1000",
		categoria = "Obbies y parkour",
		procedencia = "uncopylocked",
		placeId = 132523658595322,
	},
	{
		titulo = "Keyboard controlled police cars. UNCOPYLOCKED",
		creador = "ROBLOX",
		categoria = "Vehiculos y tycoons",
		procedencia = "uncopylocked",
		anio = 2007,
		placeId = 130560352150720,
	},
	{
		titulo = "Nooooooo",
		creador = "ROBLOX",
		categoria = "Zombis y terror",
		procedencia = "uncopylocked",
		anio = 2010,
		placeId = 75113184635972,
	},
	{
		titulo = "YOUR HOUSE IS SURROEUNDED BY ZOMBIES",
		creador = "jediknightkrazy",
		categoria = "Zombis y terror",
		procedencia = "uncopylocked",
		anio = 2009,
		placeId = 106544989670742,
	},
}
